require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/supplies", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Supply. As you add validations to Supply, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Supply.create! valid_attributes
      get supplies_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      supply = Supply.create! valid_attributes
      get supply_url(supply)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_supply_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      supply = Supply.create! valid_attributes
      get edit_supply_url(supply)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Supply" do
        expect {
          post supplies_url, params: { supply: valid_attributes }
        }.to change(Supply, :count).by(1)
      end

      it "redirects to the created supply" do
        post supplies_url, params: { supply: valid_attributes }
        expect(response).to redirect_to(supply_url(Supply.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Supply" do
        expect {
          post supplies_url, params: { supply: invalid_attributes }
        }.to change(Supply, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post supplies_url, params: { supply: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested supply" do
        supply = Supply.create! valid_attributes
        patch supply_url(supply), params: { supply: new_attributes }
        supply.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the supply" do
        supply = Supply.create! valid_attributes
        patch supply_url(supply), params: { supply: new_attributes }
        supply.reload
        expect(response).to redirect_to(supply_url(supply))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        supply = Supply.create! valid_attributes
        patch supply_url(supply), params: { supply: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested supply" do
      supply = Supply.create! valid_attributes
      expect {
        delete supply_url(supply)
      }.to change(Supply, :count).by(-1)
    end

    it "redirects to the supplies list" do
      supply = Supply.create! valid_attributes
      delete supply_url(supply)
      expect(response).to redirect_to(supplies_url)
    end
  end
end
